"""4c MCP authoring and round-trip vertical-slice acceptance.

The fixture intentionally uses only the rectangle/Profile slice from the MCP
contract.  A second, independently authored project is used to compare the
adapter's XML semantics without comparing UUIDs generated by separate runs.
"""

import copy
from decimal import Decimal, InvalidOperation
import hashlib
from importlib.util import find_spec
import json
from pathlib import Path
import re
import tempfile
import unittest
import xml.etree.ElementTree as ET
from uuid import uuid4

if find_spec("mcp") is not None:
    import anyio
    from cambam_builder.mcp_adapter.service import DocumentService
    from cambam_builder.mcp_adapter.schema import OUTPUTS
else:  # pragma: no cover - exercised only in a base-library environment
    DocumentService = None
    OUTPUTS = {}

from cambam_builder import CBProject
from cambam_builder.cambam_writer import build_xml_tree


UUID_PATTERN = re.compile(
    r"\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-"
    r"[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\b"
)
NUMBER_PATTERN = re.compile(
    r"(?<![A-Za-z])[-+]?(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eE][-+]?\d+)?(?![A-Za-z])"
)


@unittest.skipIf(DocumentService is None, "Install .[mcp] for adapter checks")
class AuthoringTests(unittest.TestCase):
    """DocumentService contract tests for the first authoring slice."""

    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)

    def run_async(self, test):
        async def run():
            self.service = DocumentService(self.root)
            await test()

        anyio.run(run)

    def args(self, **kwargs):
        result = {
            "workspace_id": self.service.workspace.id,
            "request_id": str(uuid4()),
        }
        result.update(kwargs)
        return result

    async def call(self, name, arguments):
        result = await self.service.call_tool(name, arguments)
        # During the 4b -> 4c transition an old checkout does not advertise
        # authoring outputs yet.  Once the slice is implemented, validate all
        # returned envelopes against the packaged closed schemas.
        validator = OUTPUTS.get(name)
        if validator is not None:
            validator.validate(result)
        return result

    async def create(self, name="slice"):
        result = await self.call("document_create", self.args(name=name, units="mm"))
        self.assertTrue(result["ok"], result)
        self.assertEqual(result["revision"], 0)
        self.assertEqual(result["data"], {
            "name": name,
            "units": "mm",
            "source": None,
            "counts": {"layers": 0, "parts": 0, "primitives": 0, "mops": 0},
        })
        self.assertIn("UNITS_ASSUMED", {item["code"] for item in result["diagnostics"]})
        return result["document"]

    async def inspect(self, handle, *, revision=None, limit=100):
        arguments = {
            "workspace_id": self.service.workspace.id,
            "document": handle,
            "limit": limit,
        }
        if revision is not None:
            arguments["expected_revision"] = revision
        result = await self.call("document_inspect", arguments)
        self.assertTrue(result["ok"], result)
        self.assertIsNone(result["request_id"])
        self.assertEqual(result["revision"], revision if revision is not None else result["revision"])
        return result

    async def inspect_records(self, handle, revision=None):
        result = await self.inspect(handle, revision=revision)
        self.assertIsNone(result["data"]["next_offset"])
        return result["data"]["entities"]

    @staticmethod
    def profile_arguments(**overrides):
        result = {
            "identifier": "profile",
            "part": "Part",
            "side": "Outside",
            "target_depth": -1,
            "depth_increment": 0.5,
            "tool_diameter": 3,
            "cut_feedrate": 300,
            "plunge_feedrate": 100,
            "spindle_speed": 12000,
            "clearance_plane": 5,
        }
        result.update(overrides)
        return result

    @staticmethod
    def expected_profile_parameters():
        return {
            "target_depth": -1,
            "depth_increment": 0.5,
            "tool_diameter": 3,
            "cut_feedrate": 300,
            "plunge_feedrate": 100,
            "spindle_speed": 12000,
            "stock_surface": 0,
            "clearance_plane": 5,
            "enabled": True,
            "profile_side": "Outside",
            "work_plane": "XY",
            "tool_profile": "EndMill",
            "spindle_direction": "CW",
            "velocity_mode": "ExactStop",
            "milling_direction": "Conventional",
            "roughing_clearance": 0,
            "stepover": 0.4,
            "tool_number": 0,
            "collision_detection": True,
            "corner_overcut": False,
            "final_depth_increment": 0,
            "cut_ordering": "DepthFirst",
            "lead_in_type": "None",
            "tab_method": "None",
            "tab_width": 6,
            "tab_height": 1.5,
            "tab_min_tabs": 3,
            "tab_max_tabs": 3,
            "tab_distance": 40,
            "tab_size_threshold": 4,
            "tab_use_leadins": False,
            "tab_style": "Square",
            "custom_mop_header": "",
            "custom_mop_footer": "",
        }

    @staticmethod
    def assert_cyclic_xyz(testcase, actual, expected, places=9):
        testcase.assertEqual(len(actual), len(expected))
        for offset in range(len(expected)):
            rotated = expected[offset:] + expected[:offset]
            if all(
                all(abs(float(got[index]) - float(want[index])) <= 10 ** -places
                    for index in range(3))
                for got, want in zip(actual, rotated)
            ):
                return
        testcase.fail(f"world corners differ: expected cyclic {expected!r}, got {actual!r}")

    @staticmethod
    def direct_project():
        """Build the same slice through the public framework API."""
        project = CBProject("slice")
        layer = project.add_layer("Geometry")
        rectangle = project.add_rect(
            layer=layer,
            corner=(0, 0),
            width=20,
            height=10,
            identifier="outline",
            elevation=0,
        )
        part = project.add_part(
            "Part",
            enabled=True,
            stock_width=0,
            stock_height=0,
            stock_thickness=0,
            stock_material="",
        )
        mop = project.add_profile_mop(
            part,
            targets=[rectangle],
            identifier="profile",
            name="profile",
            profile_side="Outside",
            target_depth=-1,
            depth_increment=0.5,
            tool_diameter=3,
            cut_feedrate=300,
            plunge_feedrate=100,
            spindle_speed=12000,
            stock_surface=0,
            clearance_plane=5,
            enabled=True,
            lead_in_type="None",
        )
        return project, rectangle, mop

    @staticmethod
    def xml_semantics(path):
        """Return parsed XML semantics while ignoring run-specific UUIDs."""
        root = ET.parse(path).getroot()

        def normalized_numbers(value):
            def replace(match):
                try:
                    number = Decimal(match.group(0))
                except InvalidOperation:
                    return match.group(0)
                if number == 0:
                    return "0"
                return format(number.normalize(), "f")

            return NUMBER_PATTERN.sub(replace, value)

        def normalized_text(element):
            value = (element.text or "").strip()
            if element.tag.rsplit("}", 1)[-1] == "Tag":
                try:
                    tag = json.loads(value)
                except (TypeError, ValueError):
                    return UUID_PATTERN.sub("<UUID>", value)
                if isinstance(tag, dict):
                    tag = dict(tag)
                    tag.pop("internal_id", None)
                    value = json.dumps(tag, sort_keys=True, separators=(",", ":"))
            return normalized_numbers(UUID_PATTERN.sub("<UUID>", value))

        def node(element):
            attributes = tuple(sorted(
                (key, normalized_numbers(UUID_PATTERN.sub("<UUID>", value)))
                for key, value in element.attrib.items()
            ))
            return (
                element.tag.rsplit("}", 1)[-1],
                attributes,
                normalized_text(element),
                tuple(node(child) for child in element),
            )

        return node(root)

    def test_create_author_round_trip_translate_retry_and_direct_parity(self):
        """Exercise the complete A -> open -> translate -> B contract."""

        async def test():
            handle = await self.create()

            add_rect = self.args(
                document=handle,
                expected_revision=0,
                identifier="outline",
                layer="Geometry",
                x=0,
                y=0,
                width=20,
                height=10,
                z=0,
            )
            rectangle_result = await self.call("geometry_add_rectangle", add_rect)
            self.assertTrue(rectangle_result["ok"], rectangle_result)
            self.assertEqual(rectangle_result["revision"], 1)
            self.assertEqual(rectangle_result["data"]["layer"], "Geometry")
            rectangle_id = rectangle_result["data"]["entity_id"]

            records_a1 = await self.inspect_records(handle, revision=1)
            self.assertEqual([record["kind"] for record in records_a1], ["layer", "primitive"])
            primitive_a1 = records_a1[1]
            self.assertEqual(primitive_a1["id"], rectangle_id)
            self.assertEqual(primitive_a1["identifier"], "outline")
            self.assertEqual(primitive_a1["type"], "Rect")
            self.assertEqual(primitive_a1["layer"], "Geometry")
            self.assertIsNone(primitive_a1["parent"])
            self.assertEqual(primitive_a1["children"], [])
            self.assertEqual(primitive_a1["geometry"]["bounds"], [0, 0, 20, 10])
            self.assert_cyclic_xyz(
                self,
                primitive_a1["geometry"]["world_xyz"],
                [(0, 0, 0), (20, 0, 0), (20, 10, 0), (0, 10, 0)],
            )

            profile_args = self.args(
                document=handle,
                expected_revision=1,
                targets=[rectangle_id],
                **self.profile_arguments(),
            )
            profile_result = await self.call("machining_add_profile", profile_args)
            self.assertTrue(profile_result["ok"], profile_result)
            self.assertEqual(profile_result["revision"], 2)
            self.assertEqual(profile_result["data"]["part"], "Part")
            self.assertEqual(profile_result["data"]["side"], "Outside")
            self.assertEqual(profile_result["data"]["targets"], [rectangle_id])
            mop_id = profile_result["data"]["mop_id"]

            records_a2 = await self.inspect_records(handle, revision=2)
            self.assertEqual(
                [record["kind"] for record in records_a2],
                ["layer", "part", "primitive", "mop"],
            )
            self.assertEqual(records_a2[1], {
                "kind": "part",
                "name": "Part",
                "enabled": True,
                "stock_width": 0,
                "stock_height": 0,
                "stock_thickness": 0,
                "stock_material": "",
                "stock_color": "210,180,140",
                "stock_offset": [0.0, 0.0],
                "stock_surface": 0.0,
                "machining_origin": [0.0, 0.0],
                "default_tool_diameter": None,
                "default_spindle_speed": None,
                "nest_method": "None",
                "nest_rows": 1,
                "nest_columns": 1,
                "nest_spacing": 0.0,
                "grid_order": "RightUp",
                "grid_alternate": False,
            })
            primitive_a2, mop_a2 = records_a2[2], records_a2[3]
            self.assertEqual(primitive_a2, primitive_a1)
            self.assertEqual(mop_a2["id"], mop_id)
            self.assertEqual(mop_a2["identifier"], "profile")
            self.assertEqual(mop_a2["type"], "ProfileMop")
            self.assertEqual(mop_a2["part"], "Part")
            self.assertEqual(mop_a2["targets"], [rectangle_id])
            self.assertEqual(mop_a2["parameters"], self.expected_profile_parameters())

            save_a = self.args(document=handle, expected_revision=2, path="A.cb")
            saved_a = await self.call("document_save", save_a)
            self.assertTrue(saved_a["ok"], saved_a)
            self.assertEqual(saved_a["revision"], 2)
            self.assertEqual(saved_a["data"]["path"], "A.cb")
            self.assertEqual(Path(saved_a["data"]["absolute_path"]), self.root / "A.cb")
            bytes_a = (self.root / "A.cb").read_bytes()
            self.assertEqual(saved_a["data"]["bytes"], len(bytes_a))
            self.assertEqual(saved_a["data"]["sha256"], hashlib.sha256(bytes_a).hexdigest())
            self.assertIn("INTERCHANGE_LIMITED", {item["code"] for item in saved_a["diagnostics"]})

            direct, direct_rectangle, _ = self.direct_project()
            direct_a = self.root / "direct-A.cb"
            direct.save(str(direct_a))
            self.assertEqual(self.xml_semantics(self.root / "A.cb"), self.xml_semantics(direct_a))
            self.assert_cyclic_xyz(
                self,
                direct_rectangle.get_absolute_coordinates_xyz(),
                [(0, 0, 0), (20, 0, 0), (20, 10, 0), (0, 10, 0)],
            )

            opened = await self.call("document_open", self.args(path="A.cb", units="mm"))
            self.assertTrue(opened["ok"], opened)
            reopened = opened["document"]
            self.assertNotEqual(reopened, handle)
            self.assertEqual(opened["revision"], 0)
            self.assertEqual(opened["data"]["source"], {
                "path": "A.cb",
                "sha256": saved_a["data"]["sha256"],
            })
            records_open = await self.inspect_records(reopened, revision=0)
            self.assertEqual(records_open, records_a2)

            translate = self.args(
                document=reopened,
                expected_revision=0,
                entity_id=rectangle_id,
                dx=5,
                dy=2,
            )
            translated = await self.call("geometry_translate", translate)
            self.assertTrue(translated["ok"], translated)
            self.assertEqual(translated["revision"], 1)
            self.assertEqual(translated["data"], {"entity_id": rectangle_id})
            records_b = await self.inspect_records(reopened, revision=1)
            self.assertEqual(records_b[0:2], records_a2[0:2])
            self.assertEqual(records_b[3], records_a2[3])
            self.assert_cyclic_xyz(
                self,
                records_b[2]["geometry"]["world_xyz"],
                [(5, 2, 0), (25, 2, 0), (25, 12, 0), (5, 12, 0)],
            )
            self.assertEqual(records_b[2]["geometry"]["bounds"], [5, 2, 25, 12])
            self.assertEqual(records_b[2]["id"], rectangle_id)
            self.assertEqual(records_b[3]["id"], mop_id)
            self.assertEqual(records_b[3]["targets"], [rectangle_id])
            self.assertEqual(records_b[3]["parameters"], mop_a2["parameters"])

            replayed_translate = await self.call("geometry_translate", translate)
            self.assertEqual(replayed_translate, {**translated, "replayed": True})
            self.assertEqual(await self.inspect_records(reopened, revision=1), records_b)
            self.assertEqual((self.root / "A.cb").read_bytes(), bytes_a)

            save_b = self.args(document=reopened, expected_revision=1, path="B.cb")
            saved_b = await self.call("document_save", save_b)
            self.assertTrue(saved_b["ok"], saved_b)
            self.assertEqual(saved_b["revision"], 1)
            bytes_b = (self.root / "B.cb").read_bytes()
            self.assertEqual(saved_b["data"]["sha256"], hashlib.sha256(bytes_b).hexdigest())
            self.assertNotEqual(bytes_a, bytes_b)
            self.assertEqual((self.root / "A.cb").read_bytes(), bytes_a)

            direct.translate_primitive(direct_rectangle, 5, 2, bake=False)
            direct_b = self.root / "direct-B.cb"
            direct.save(str(direct_b))
            self.assertEqual(self.xml_semantics(self.root / "B.cb"), self.xml_semantics(direct_b))
            self.assert_cyclic_xyz(
                self,
                direct_rectangle.get_absolute_coordinates_xyz(),
                [(5, 2, 0), (25, 2, 0), (25, 12, 0), (5, 12, 0)],
            )

        self.run_async(test)

    def test_profile_corner_overcut_is_authorable_and_inspectable(self):
        async def test():
            handle = await self.create("corner-overcut")
            rectangle = await self.call("geometry_add_rectangle", self.args(
                document=handle, expected_revision=0, identifier="outline",
                layer="Geometry", x=0, y=0, width=20, height=10, z=0))
            self.assertTrue(rectangle["ok"], rectangle)
            profile = await self.call("machining_add_profile", self.args(
                document=handle, expected_revision=1,
                targets=[rectangle["data"]["entity_id"]],
                **self.profile_arguments(corner_overcut=True)))
            self.assertTrue(profile["ok"], profile)
            records = await self.inspect_records(handle, revision=2)
            mop = next(record for record in records if record["kind"] == "mop")
            self.assertTrue(mop["parameters"]["corner_overcut"])

        self.run_async(test)

    def test_part_stock_nesting_and_layer_properties_are_explicitly_configurable(self):
        async def test():
            handle = await self.create("settings")
            layer = await self.call("document_set_layer_properties", self.args(
                document=handle, expected_revision=0, layer="Geometry",
                color="White", alpha=0.8, pen_width=1.5, visible=True, locked=False))
            self.assertTrue(layer["ok"], layer)
            part = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=1, part="Sheet",
                stock_width=1220, stock_height=2440, stock_thickness=9,
                stock_material="Plywood", stock_color="210,180,140",
                nest_method="Grid", nest_rows=3, nest_columns=3,
                nest_spacing=40, grid_order="RightUp", grid_alternate=False))
            self.assertTrue(part["ok"], part)
            self.assertEqual(part["data"]["nest_method"], "Grid")
            inspected = await self.inspect_records(handle, revision=2)
            layer_record = next(item for item in inspected if item["kind"] == "layer")
            part_record = next(item for item in inspected if item["kind"] == "part")
            self.assertEqual(layer_record["color"], "White")
            self.assertEqual(part_record["stock_thickness"], 9)
            self.assertEqual(part_record["nest_rows"], 3)
            exported = await self.call("document_export", {
                "workspace_id": self.service.workspace.id, "document": handle,
                "expected_revision": 2, "suggested_filename": "settings.cb"})
            self.assertIn('<NestMethod>Grid</NestMethod>', exported["data"]["content"])
            self.assertIn('<Rows>3</Rows>', exported["data"]["content"])
            self.assertIn('<GridDirectionAlternate>false</GridDirectionAlternate>', exported["data"]["content"])
            self.assertIn('color="White"', exported["data"]["content"])
        self.run_async(test)

    def test_native_zero_values_stock_coordinates_and_nesting_variants_are_inspectable(self):
        async def test():
            source = CBProject("native-part-settings")
            source.add_layer("Geometry", pen_width=0)
            orders = (
                "RightUp", "RightDown", "LeftUp", "LeftDown",
                "UpRight", "UpLeft", "DownRight", "DownLeft",
            )
            for index, order in enumerate(orders):
                source.add_part(
                    f"P{index}", stock_width=0, stock_height=0,
                    stock_thickness=0, stock_material="",
                    default_tool_diameter=0,
                    nesting_method="Manual" if index % 2 == 0 else "PointList",
                    nesting_grid_order=order,
                    stock_offset=(12.5, -3.0), stock_surface=7.25,
                )
            tree = build_xml_tree(source)
            native_nesting = tree.getroot().find("./parts/part/Nesting")
            native_nesting.find("BasePoint").text = "3,4"
            ET.SubElement(native_nesting, "PointListID").text = "42"
            ET.SubElement(native_nesting, "GCodeOrder").text = "2,1,0"
            content = ET.tostring(tree.getroot(), encoding="unicode")

            imported = await self.call("document_import", self.args(
                units="mm", source_name="native-part-settings.cb", content=content))
            self.assertTrue(imported["ok"], imported)
            handle = imported["document"]
            records = await self.inspect_records(handle, revision=0)
            layer = next(record for record in records if record["kind"] == "layer")
            self.assertEqual(0, layer["pen_width"])
            parts = [record for record in records if record["kind"] == "part"]
            self.assertEqual(list(orders), [record["grid_order"] for record in parts])
            self.assertEqual(
                ["Manual", "PointList"] * 4,
                [record["nest_method"] for record in parts],
            )
            for record in parts:
                self.assertEqual(0, record["default_tool_diameter"])
                self.assertEqual([12.5, -3.0], record["stock_offset"])
                self.assertEqual(7.25, record["stock_surface"])

            # A nesting-only patch keeps all omitted Part/stock values and the
            # native settings the core model does not author itself.
            configured = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=0, part="P0", nest_rows=7))
            self.assertTrue(configured["ok"], configured)
            self.assertEqual("Manual", configured["data"]["nest_method"])
            self.assertEqual(0, configured["data"]["default_tool_diameter"])
            self.assertEqual(12.5, configured["data"]["stock_offset_x"])
            self.assertEqual(-3.0, configured["data"]["stock_offset_y"])
            self.assertEqual(7.25, configured["data"]["stock_surface"])

            exported = await self.call("document_export", {
                "workspace_id": self.service.workspace.id, "document": handle,
                "expected_revision": 1, "suggested_filename": "native-patched.cb",
            })
            self.assertTrue(exported["ok"], exported)
            exported_part = ET.fromstring(exported["data"]["content"]).find(
                "./parts/part[@Name='P0']"
            )
            self.assertEqual("12.5,-3.0,7.25", exported_part.findtext("Stock/PMin"))
            self.assertEqual("12.5,-3.0,7.25", exported_part.findtext("Stock/PMax"))
            self.assertEqual("3,4", exported_part.findtext("Nesting/BasePoint"))
            self.assertEqual("42", exported_part.findtext("Nesting/PointListID"))
            self.assertEqual("2,1,0", exported_part.findtext("Nesting/GCodeOrder"))
            self.assertEqual("7", exported_part.findtext("Nesting/Rows"))

        self.run_async(test)

    def test_configure_part_is_a_patch_and_minimal_creation_uses_undefined_stock(self):
        async def test():
            handle = await self.create("part-patch")
            created = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=0, part="Part"))
            self.assertTrue(created["ok"], created)
            self.assertEqual(0, created["data"]["stock_width"])
            self.assertEqual(0, created["data"]["stock_height"])
            self.assertEqual(0, created["data"]["stock_thickness"])
            self.assertEqual("", created["data"]["stock_material"])

            configured = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=1, part="Part",
                stock_width=100, stock_height=50, stock_thickness=8,
                stock_material="Aluminum", stock_offset_x=2,
                stock_offset_y=3, stock_surface=4,
                default_tool_diameter=0, nest_method="Grid",
                grid_order="DownLeft"))
            self.assertTrue(configured["ok"], configured)
            patched = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=2, part="Part", enabled=False))
            self.assertTrue(patched["ok"], patched)
            self.assertEqual(100, patched["data"]["stock_width"])
            self.assertEqual(0, patched["data"]["default_tool_diameter"])
            self.assertEqual("Grid", patched["data"]["nest_method"])
            self.assertEqual("DownLeft", patched["data"]["grid_order"])
            self.assertEqual(2, patched["data"]["stock_offset_x"])
            self.assertEqual(4, patched["data"]["stock_surface"])

        self.run_async(test)

    def test_settings_tools_report_cross_entity_identifier_conflicts(self):
        async def test():
            handle = await self.create("settings-conflicts")
            rectangle = await self.call("geometry_add_rectangle", self.args(
                document=handle, expected_revision=0, identifier="outline",
                layer="Geometry", x=0, y=0, width=20, height=10, z=0))
            self.assertTrue(rectangle["ok"], rectangle)

            layer_conflict = await self.call("document_set_layer_properties", self.args(
                document=handle, expected_revision=1, layer="outline", color="White"))
            self.assertFalse(layer_conflict["ok"])
            self.assertEqual(layer_conflict["error"]["code"], "IDENTIFIER_CONFLICT")
            self.assertEqual(layer_conflict["error"]["field"], "layer")

            part_conflict = await self.call("machining_configure_part", self.args(
                document=handle, expected_revision=1, part="outline",
                stock_width=1220, stock_height=2440, stock_thickness=9,
                stock_material="Plywood"))
            self.assertFalse(part_conflict["ok"])
            self.assertEqual(part_conflict["error"]["code"], "IDENTIFIER_CONFLICT")
            self.assertEqual(part_conflict["error"]["field"], "part")

            unchanged = await self.inspect(handle, revision=1)
            self.assertEqual(unchanged["data"]["summary"]["counts"]["parts"], 0)
            self.assertEqual(unchanged["data"]["summary"]["counts"]["layers"], 1)
        self.run_async(test)

    def test_imported_part_can_be_reconfigured_exported_and_strictly_reimported(self):
        async def test():
            source = CBProject("imported-part")
            source.add_part(
                "Sheet", enabled=True, stock_width=100, stock_height=200,
                stock_thickness=3, stock_material="MDF", stock_color="1,2,3",
                machining_origin=(4, 5), default_tool_diameter=6,
                nesting_method="Grid", nesting_rows=2, nesting_columns=3,
                nesting_spacing=7, nesting_grid_order="RightUp",
                nesting_grid_alternate=False,
            )
            source_path = self.root / "imported-part-source.cb"
            source.save(str(source_path))
            imported = await self.call("document_import", self.args(
                units="mm", source_name=source_path.name,
                content=source_path.read_text(encoding="utf-8")))
            self.assertTrue(imported["ok"], imported)

            configured = await self.call("machining_configure_part", self.args(
                document=imported["document"], expected_revision=0, part="Sheet",
                enabled=False, stock_width=321, stock_height=654,
                stock_thickness=7, stock_material="Aluminum", stock_color="9,8,7",
                machining_origin_x=11, machining_origin_y=13,
                default_tool_diameter=8.5, default_spindle_speed=1234,
                nest_method="IsoGrid", nest_rows=4, nest_columns=5,
                nest_spacing=6.25, grid_order="LeftDown", grid_alternate=True))
            self.assertTrue(configured["ok"], configured)
            self.assertIn(
                "SESSION_ONLY_SETTING",
                {item["code"] for item in configured["diagnostics"]},
            )

            exported = await self.call("document_export", {
                "workspace_id": self.service.workspace.id,
                "document": imported["document"], "expected_revision": 1,
                "suggested_filename": "reconfigured-part.cb",
            })
            self.assertTrue(exported["ok"], exported)
            reimported = await self.call("document_import", self.args(
                units="mm", source_name="reconfigured-part.cb",
                content=exported["data"]["content"]))
            self.assertTrue(reimported["ok"], reimported)
            records = await self.inspect_records(reimported["document"], revision=0)
            part = next(record for record in records if record["kind"] == "part")
            self.assertEqual({key: part[key] for key in (
                "name", "enabled", "stock_width", "stock_height", "stock_thickness",
                "stock_material", "stock_color", "machining_origin",
                "default_tool_diameter", "nest_method", "nest_rows", "nest_columns",
                "nest_spacing", "grid_order", "grid_alternate",
            )}, {
                "name": "Sheet", "enabled": False, "stock_width": 321,
                "stock_height": 654, "stock_thickness": 7,
                "stock_material": "Aluminum", "stock_color": "9,8,7",
                "machining_origin": [11, 13], "default_tool_diameter": 8.5,
                "nest_method": "IsoGrid", "nest_rows": 4, "nest_columns": 5,
                "nest_spacing": 6.25, "grid_order": "LeftDown",
                "grid_alternate": True,
            })
        self.run_async(test)

    def test_invalid_references_identifier_conflicts_retries_and_atomic_failure(self):
        async def test():
            handle = await self.create()

            for tool in ("geometry_add_rectangle", "geometry_add_circle", "geometry_add_arc",
                         "geometry_add_pline", "geometry_add_points", "geometry_translate",
                         "machining_add_profile"):
                malformed = await self.call(tool, {})
                self.assertFalse(malformed["ok"])
                self.assertIsNone(malformed["document"])
                self.assertIsNone(malformed["request_id"])
                self.assertEqual(malformed["workspace_id"], self.service.workspace.id)
                self.assertEqual(malformed["error"]["code"], "INVALID_ARGUMENT")

            missing_field = self.args(
                document=handle,
                expected_revision=0,
                identifier="incomplete",
                layer="Geometry",
                x=0,
                y=0,
                width=20,
            )
            failed = await self.call("geometry_add_rectangle", missing_field)
            self.assertEqual(failed["error"]["code"], "INVALID_ARGUMENT")
            self.assertEqual((await self.inspect(handle, revision=0))["data"]["summary"]["counts"], {
                "layers": 0,
                "parts": 0,
                "primitives": 0,
                "mops": 0,
            })

            rectangle_args = self.args(
                document=handle,
                expected_revision=0,
                identifier="outline",
                layer="Geometry",
                x=0,
                y=0,
                width=20,
                height=10,
            )
            rectangle = await self.call("geometry_add_rectangle", rectangle_args)
            self.assertTrue(rectangle["ok"], rectangle)
            rectangle_id = rectangle["data"]["entity_id"]
            self.assertEqual(rectangle["revision"], 1)
            self.assertEqual(await self.call("geometry_add_rectangle", rectangle_args), {
                **rectangle,
                "replayed": True,
            })
            self.assertEqual((await self.inspect(handle))["revision"], 1)

            stale_rect = await self.call("geometry_add_rectangle", {
                **rectangle_args,
                "request_id": str(uuid4()),
            })
            self.assertEqual(stale_rect["error"]["code"], "STALE_REVISION")
            duplicate_rect = await self.call("geometry_add_rectangle", {
                **rectangle_args,
                "request_id": str(uuid4()),
                "expected_revision": 1,
            })
            self.assertEqual(duplicate_rect["error"]["code"], "IDENTIFIER_CONFLICT")

            profile_args = self.args(
                document=handle,
                expected_revision=1,
                targets=[rectangle_id],
                **self.profile_arguments(),
            )
            profile = await self.call("machining_add_profile", profile_args)
            self.assertTrue(profile["ok"], profile)
            mop_id = profile["data"]["mop_id"]
            self.assertEqual(profile["revision"], 2)
            self.assertEqual(await self.call("machining_add_profile", profile_args), {
                **profile,
                "replayed": True,
            })

            duplicate_profile = await self.call("machining_add_profile", {
                **profile_args,
                "request_id": str(uuid4()),
                "expected_revision": 2,
            })
            self.assertEqual(duplicate_profile["error"]["code"], "IDENTIFIER_CONFLICT")

            duplicate_targets = await self.call("machining_add_profile", {
                **profile_args,
                "request_id": str(uuid4()),
                "expected_revision": 2,
                "identifier": "duplicate-targets",
                "targets": [rectangle_id, rectangle_id],
            })
            self.assertEqual(duplicate_targets["error"]["code"], "INVALID_ARGUMENT")

            missing_target = await self.call("machining_add_profile", {
                **profile_args,
                "request_id": str(uuid4()),
                "expected_revision": 2,
                "identifier": "missing-target",
                "targets": [str(uuid4())],
            })
            self.assertEqual(missing_target["error"]["code"], "ENTITY_NOT_FOUND")

            wrong_kind = await self.call("machining_add_profile", {
                **profile_args,
                "request_id": str(uuid4()),
                "expected_revision": 2,
                "identifier": "wrong-kind",
                "targets": [mop_id],
            })
            self.assertEqual(wrong_kind["error"]["code"], "UNSUPPORTED_OPERATION")

            identifier_conflict_across_kinds = await self.call("geometry_add_rectangle", {
                **rectangle_args,
                "request_id": str(uuid4()),
                "expected_revision": 2,
                "identifier": "Part",
            })
            self.assertEqual(identifier_conflict_across_kinds["error"]["code"], "IDENTIFIER_CONFLICT")
            self.assertIn("already used by Part",
                          identifier_conflict_across_kinds["error"]["message"])
            self.assertIn("project-unique identifier",
                          identifier_conflict_across_kinds["error"]["message"])

            before_translate_failure = await self.inspect(handle, revision=2)
            before_records = copy.deepcopy(before_translate_failure["data"]["entities"])
            stale_translate = await self.call("geometry_translate", self.args(
                document=handle,
                expected_revision=1,
                entity_id=rectangle_id,
                dx=5,
                dy=2,
            ))
            self.assertEqual(stale_translate["error"]["code"], "STALE_REVISION")
            missing_translate = await self.call("geometry_translate", self.args(
                document=handle,
                expected_revision=2,
                entity_id=str(uuid4()),
                dx=5,
                dy=2,
            ))
            self.assertEqual(missing_translate["error"]["code"], "ENTITY_NOT_FOUND")
            after_failed_translate = await self.inspect(handle, revision=2)
            self.assertEqual(after_failed_translate["data"]["entities"], before_records)

            translate = self.args(
                document=handle,
                expected_revision=2,
                entity_id=rectangle_id,
                dx=5,
                dy=2,
            )
            translated = await self.call("geometry_translate", translate)
            self.assertTrue(translated["ok"], translated)
            self.assertEqual(translated["revision"], 3)
            self.assertEqual(await self.call("geometry_translate", translate), {
                **translated,
                "replayed": True,
            })
            before_failed_profile = await self.inspect(handle, revision=3)

            invalid_depth = await self.call("machining_add_profile", {
                **profile_args,
                "request_id": str(uuid4()),
                "expected_revision": 3,
                "identifier": "invalid-depth",
                "target_depth": 0,
            })
            self.assertEqual(invalid_depth["error"]["code"], "INVALID_ARGUMENT")
            after_failed_profile = await self.inspect(handle, revision=3)
            self.assertEqual(
                after_failed_profile["data"],
                before_failed_profile["data"],
            )
            self.assertEqual(after_failed_profile["revision"], 3)

        self.run_async(test)

    def test_same_revision_mutations_are_serialized(self):
        async def test():
            handle = await self.create()
            common = {
                "document": handle,
                "expected_revision": 0,
                "layer": "Geometry",
                "x": 0,
                "y": 0,
                "width": 20,
                "height": 10,
            }
            requests = [
                self.args(**common, identifier="first"),
                self.args(**common, identifier="second"),
            ]
            results = []

            async def add(arguments):
                results.append(await self.call("geometry_add_rectangle", arguments))

            async with anyio.create_task_group() as group:
                for arguments in requests:
                    group.start_soon(add, arguments)

            self.assertEqual(sum(result["ok"] for result in results), 1)
            self.assertEqual(
                sum(not result["ok"] and result["error"]["code"] == "STALE_REVISION"
                    for result in results),
                1,
            )
            self.assertEqual((await self.inspect(handle, revision=1))["data"]["summary"]["counts"], {
                "layers": 1,
                "parts": 0,
                "primitives": 1,
                "mops": 0,
            })

        self.run_async(test)

    def test_profile_rejects_transformed_out_of_scope_target_atomically(self):
        async def test():
            source = CBProject("transformed")
            layer = source.add_layer("Geometry")
            rectangle = source.add_rect(layer, identifier="stretched", width=20, height=10)
            self.assertTrue(source.scale_primitive(rectangle, 2, 1, bake=False))
            source_path = self.root / "transformed.cb"
            source.save(str(source_path))

            opened = await self.call("document_open", self.args(path="transformed.cb", units="mm"))
            self.assertTrue(opened["ok"], opened)
            handle = opened["document"]
            records_before = await self.inspect_records(handle, revision=0)
            rectangle_id = next(record["id"] for record in records_before if record["kind"] == "primitive")
            self.assertIsNone(next(record for record in records_before if record["kind"] == "primitive")["geometry"])

            rejected = await self.call("machining_add_profile", self.args(
                document=handle,
                expected_revision=0,
                targets=[rectangle_id],
                **self.profile_arguments(identifier="stretched-profile"),
            ))
            self.assertEqual(rejected["error"]["code"], "UNSUPPORTED_OPERATION")
            records_after = await self.inspect_records(handle, revision=0)
            self.assertEqual(records_after, records_before)

        self.run_async(test)

    def test_typed_inspection_is_explicitly_unsupported_for_other_shapes_and_settings(self):
        """Identity/relationships remain inspectable without invented details."""

        async def test():
            source = CBProject("unsupported")
            source.add_layer("Geometry")
            note = source.add_text(
                "Geometry", text="private note", position=(5, 5), height=4,
                identifier="note",
            )
            self.assertTrue(source.scale_primitive(note, 2, 1, bake=False))
            part = source.add_part(
                "Part",
                enabled=True,
                stock_width=0,
                stock_height=0,
                stock_thickness=0,
                stock_material="",
            )
            profile_mop = source.add_profile_mop(
                part,
                targets=[note],
                identifier="inherited-profile",
                name="inherited-profile",
                profile_side="Outside",
                target_depth=-1,
                depth_increment=0.5,
                tool_diameter=3,
                cut_feedrate=300,
                plunge_feedrate=100,
                spindle_speed=12000,
                stock_surface=0,
                clearance_plane=5,
                lead_in_type="None",
                # This public field is fixed but not returned by the closed record.
                optimisation_mode="Experimental",
            )
            source_path = self.root / "unsupported.cb"
            source.save(str(source_path))

            opened = await self.call("document_open", self.args(path="unsupported.cb", units="mm"))
            self.assertTrue(opened["ok"], opened)
            records = await self.inspect_records(opened["document"], revision=0)
            self.assertEqual([record["kind"] for record in records], ["layer", "part", "primitive", "mop"])
            primitive, mop_record = records[2], records[3]
            self.assertEqual(primitive["identifier"], "note")
            self.assertEqual(primitive["type"], "Text")
            self.assertIsNone(primitive["geometry"])
            self.assertEqual(mop_record["identifier"], "inherited-profile")
            self.assertEqual(mop_record["type"], "ProfileMop")
            self.assertEqual(mop_record["targets"], [primitive["id"]])
            self.assertEqual(mop_record["parameters"], {})
            self.assertIn(
                "INSPECTION_UNSUPPORTED",
                {item["code"] for item in (await self.inspect(opened["document"]))[
                    "diagnostics"
                ]},
            )

            # Matching public values are still unsupported when a native
            # container inherits instead of explicitly selecting Value.
            profile_mop.optimisation_mode = "Standard"
            inherited_path = self.root / "inherited.cb"
            source.save(str(inherited_path))
            tree = ET.parse(inherited_path)
            tree.getroot().find(".//HoldingTabs").set("state", "Default")
            tree.write(inherited_path, encoding="utf-8", xml_declaration=True)
            inherited = await self.call(
                "document_open", self.args(path="inherited.cb", units="mm")
            )
            self.assertTrue(inherited["ok"], inherited)
            inherited_records = await self.inspect_records(
                inherited["document"], revision=0
            )
            self.assertEqual(inherited_records[3]["parameters"], {})
            self.assertIn(
                "INSPECTION_UNSUPPORTED",
                {item["code"] for item in (await self.inspect(inherited["document"]))[
                    "diagnostics"
                ]},
            )

        self.run_async(test)


if __name__ == "__main__":
    unittest.main()
