"""Compatibility facade for the canonical entity implementation modules."""

from .native.core import (
    ARC_ANGLE_TOLERANCE_RADIANS,
    ARC_SWEEP_TOLERANCE_DEGREES,
    CURVE_POINT_TOLERANCE,
    PLINE_BULGE_TOLERANCE,
    BoundingBox,
    CamBamEntity,
    Primitive,
    Vertex,
    VertexInput,
)
from .native.cad import Arc, Circle, Layer, Pline, Points, Rect, Text
from .native.region import Region
from .native.cam import (
    MOP_COMMON_FIELD_POLICIES,
    MOP_DRILL_FIELD_POLICIES,
    MOP_ENGRAVE_FIELD_POLICIES,
    MOP_POCKET_FIELD_POLICIES,
    MOP_PROFILE_FIELD_POLICIES,
    MOP_XML_FIELD_PATHS,
    MOP_XML_PATH_TO_FIELD,
    DrillMop,
    EngraveMop,
    Mop,
    MopType,
    MopFieldEncodingPolicy,
    MopSubtypeFieldEncodingPolicy,
    Part,
    PocketMop,
    ProfileMop,
)

__all__ = [
    "ARC_ANGLE_TOLERANCE_RADIANS",
    "ARC_SWEEP_TOLERANCE_DEGREES",
    "CURVE_POINT_TOLERANCE",
    "PLINE_BULGE_TOLERANCE",
    "BoundingBox",
    "CamBamEntity",
    "Primitive",
    "Vertex",
    "VertexInput",
    "Layer",
    "Pline",
    "Circle",
    "Rect",
    "Arc",
    "Points",
    "Text",
    "Region",
    "Part",
    "Mop",
    "MopType",
    "ProfileMop",
    "PocketMop",
    "EngraveMop",
    "DrillMop",
    "MopFieldEncodingPolicy",
    "MopSubtypeFieldEncodingPolicy",
    "MOP_XML_FIELD_PATHS",
    "MOP_XML_PATH_TO_FIELD",
    "MOP_COMMON_FIELD_POLICIES",
    "MOP_PROFILE_FIELD_POLICIES",
    "MOP_POCKET_FIELD_POLICIES",
    "MOP_ENGRAVE_FIELD_POLICIES",
    "MOP_DRILL_FIELD_POLICIES",
]
